
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 31 19:49:29 CST 2020
//----------------------------------------------------

package gramaticaC;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int scanfFloat = 48;
  public static final int condBreak = 12;
  public static final int visual = 14;
  public static final int printf = 45;
  public static final int comilla = 18;
  public static final int ampersand = 35;
  public static final int main = 30;
  public static final int condCase = 40;
  public static final int dosPuntos = 5;
  public static final int condWhile = 43;
  public static final int llave_b = 7;
  public static final int llave_a = 6;
  public static final int coma = 2;
  public static final int igual = 33;
  public static final int condSwitch = 39;
  public static final int numeral = 55;
  public static final int tipoChar = 26;
  public static final int condIf = 37;
  public static final int clscr = 50;
  public static final int numero = 52;
  public static final int comentario_c = 61;
  public static final int getch = 51;
  public static final int tipoInteger = 27;
  public static final int comentario_b = 60;
  public static final int comentario_a = 58;
  public static final int scanfChar = 49;
  public static final int menos = 21;
  public static final int menor = 32;
  public static final int EOF = 0;
  public static final int scanfInt = 47;
  public static final int mas = 20;
  public static final int verdadero = 56;
  public static final int error = 1;
  public static final int mayor = 31;
  public static final int or = 63;
  public static final int condDef = 41;
  public static final int por = 22;
  public static final int punto = 3;
  public static final int condElse = 38;
  public static final int pleca = 36;
  public static final int tipoFloat = 28;
  public static final int id = 53;
  public static final int puntoComa = 4;
  public static final int falso = 57;
  public static final int parentesis_b = 9;
  public static final int parentesis_a = 8;
  public static final int java = 16;
  public static final int and = 62;
  public static final int python = 15;
  public static final int comillaSimple = 19;
  public static final int div = 23;
  public static final int tipoVoid = 25;
  public static final int enter = 59;
  public static final int resto = 54;
  public static final int condDo = 44;
  public static final int principal = 17;
  public static final int admiracion = 34;
  public static final int condInclude = 13;
  public static final int agrupacion_b = 11;
  public static final int agrupacion_a = 10;
  public static final int condFor = 42;
  public static final int tipoConst = 29;
  public static final int scanf = 46;
  public static final int modulo = 24;
}

