
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 10 23:57:22 CST 2020
//----------------------------------------------------

package gramaticaVB;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int condNot = 25;
  public static final int condAnd = 23;
  public static final int condSelect = 60;
  public static final int condTP = 59;
  public static final int comilla = 32;
  public static final int ampersand = 64;
  public static final int condCase = 61;
  public static final int condReturn = 58;
  public static final int tipoDim = 6;
  public static final int dosPuntos = 51;
  public static final int mensaje2 = 30;
  public static final int condWhile = 17;
  public static final int intInput = 26;
  public static final int coma = 2;
  public static final int charInput = 27;
  public static final int igual = 37;
  public static final int condIs = 45;
  public static final int condOr = 24;
  public static final int menorIgual = 40;
  public static final int condNext = 22;
  public static final int condLoop = 18;
  public static final int condElseIf = 63;
  public static final int tipoChar = 9;
  public static final int condIf = 12;
  public static final int contraDiagonal = 57;
  public static final int tipoFuncion = 11;
  public static final int numero = 53;
  public static final int comentario_c = 68;
  public static final int comentario_b = 67;
  public static final int comentario_a = 66;
  public static final int menos = 34;
  public static final int menor = 38;
  public static final int condLike = 44;
  public static final int EOF = 0;
  public static final int condIsNot = 46;
  public static final int mas = 33;
  public static final int mayorIgual = 41;
  public static final int error = 1;
  public static final int tipoPublic = 4;
  public static final int mayor = 39;
  public static final int tipoSub = 10;
  public static final int por = 35;
  public static final int punto = 3;
  public static final int mensaje = 29;
  public static final int condElse = 14;
  public static final int tipoFloat = 8;
  public static final int potencia = 56;
  public static final int id = 54;
  public static final int parentesis_b = 48;
  public static final int parentesis_a = 47;
  public static final int condTo = 20;
  public static final int condThen = 13;
  public static final int fin = 5;
  public static final int mayorIgual2 = 43;
  public static final int floatInput = 28;
  public static final int condUntil = 62;
  public static final int tipoInt = 7;
  public static final int condAs = 15;
  public static final int comillaSimple = 31;
  public static final int div = 36;
  public static final int resto = 55;
  public static final int enter = 52;
  public static final int condStep = 21;
  public static final int agrupacion_b = 50;
  public static final int menorIgual2 = 42;
  public static final int condDo = 16;
  public static final int agrupacion_a = 49;
  public static final int condFor = 19;
  public static final int modulo = 65;
}

