
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 01 00:31:10 CST 2020
//----------------------------------------------------

package gramaticaPYTHON;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comilla = 16;
  public static final int condReturn = 30;
  public static final int dosPuntos = 15;
  public static final int condWhile = 34;
  public static final int intInput = 37;
  public static final int llave_b = 12;
  public static final int charInput = 38;
  public static final int llave_a = 11;
  public static final int coma = 2;
  public static final int igual = 19;
  public static final int condPass = 47;
  public static final int condIn = 32;
  public static final int menorIgual = 22;
  public static final int condIf = 35;
  public static final int numero = 41;
  public static final int comentario_c = 51;
  public static final int comentario_b = 50;
  public static final int comentario_a = 49;
  public static final int menos = 5;
  public static final int menor = 20;
  public static final int porcentaje = 8;
  public static final int EOF = 0;
  public static final int condDel = 45;
  public static final int mas = 4;
  public static final int mayorIgual = 23;
  public static final int error = 1;
  public static final int condEnd = 44;
  public static final int mayor = 21;
  public static final int condDef = 40;
  public static final int or = 25;
  public static final int por = 6;
  public static final int punto = 3;
  public static final int mensaje = 27;
  public static final int condElse = 29;
  public static final int id = 42;
  public static final int parentesis_b = 10;
  public static final int condRange = 33;
  public static final int parentesis_a = 9;
  public static final int floatInput = 39;
  public static final int and = 24;
  public static final int not = 26;
  public static final int tab = 46;
  public static final int comillaSimple = 17;
  public static final int condElif = 36;
  public static final int div = 7;
  public static final int enter = 48;
  public static final int resto = 43;
  public static final int f = 28;
  public static final int admiracion = 18;
  public static final int agrupacion_b = 14;
  public static final int agrupacion_a = 13;
  public static final int condFor = 31;
}

