
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 06 17:16:02 CST 2020
//----------------------------------------------------

package gramaticaJAVA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comilla = 31;
  public static final int noCase = 42;
  public static final int ampersand = 29;
  public static final int condReturn = 50;
  public static final int mensaje2 = 46;
  public static final int dosPuntos = 21;
  public static final int condWhile = 11;
  public static final int intInput = 47;
  public static final int llave_b = 17;
  public static final int charInput = 48;
  public static final int llave_a = 16;
  public static final int coma = 2;
  public static final int igual = 23;
  public static final int condSwitch = 13;
  public static final int condFalse = 51;
  public static final int condThis = 58;
  public static final int def = 43;
  public static final int tipoChar = 5;
  public static final int condIf = 8;
  public static final int clase = 15;
  public static final int numero = 33;
  public static final int comentario_c = 57;
  public static final int comentario_b = 56;
  public static final int comentario_a = 55;
  public static final int condTrue = 52;
  public static final int menos = 25;
  public static final int menor = 37;
  public static final int porcentaje = 28;
  public static final int EOF = 0;
  public static final int mas = 24;
  public static final int error = 1;
  public static final int tipoPublic = 14;
  public static final int mayor = 36;
  public static final int or = 54;
  public static final int guionBajo = 32;
  public static final int por = 26;
  public static final int mensaje = 45;
  public static final int punto = 3;
  public static final int condElse = 9;
  public static final int pleca = 30;
  public static final int tipoFloat = 6;
  public static final int id = 34;
  public static final int puntoComa = 20;
  public static final int parentesis_b = 41;
  public static final int parentesis_a = 40;
  public static final int quiebre = 39;
  public static final int floatInput = 49;
  public static final int and = 53;
  public static final int tipoInt = 4;
  public static final int comillaSimple = 38;
  public static final int div = 27;
  public static final int tipoVoid = 7;
  public static final int enter = 59;
  public static final int resto = 35;
  public static final int admiracion = 22;
  public static final int agrupacion_b = 19;
  public static final int condDo = 12;
  public static final int agrupacion_a = 18;
  public static final int condFor = 10;
  public static final int retorno = 44;
}

