/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Tablas.DatosVar;
import Tablas.TablaSimbolos;
import gramaticaC.AnalizadorLexico4;
import gramaticaC.SintaxC;
import gramaticaJAVA.AnalizadorLexico;
import gramaticaJAVA.SintaxJAVA;
import gramaticaPYTHON.AnalizadorLexico2;
import gramaticaPYTHON.SintaxPYTHON;
import gramaticaVB.AnalizadorLexico3;
import gramaticaVB.SintaxVB;
import hojas.NumeracionLineas;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisGonzalez
 */
public class PanelPrincipal extends javax.swing.JPanel {

    private NumeracionLineas numeracion;
    private TablaSimbolos tabla = new TablaSimbolos();
    private ManejoTexto divTexto = new ManejoTexto();

    public static String codigoPython = "";
    public static String codigoJava = "";
    public static String codigoVb = "";
    public static String codigoC = "";

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(String texto, String path) {
        initComponents();
        txtTexto.setText(texto);
        numeracion = new NumeracionLineas(txtTexto);
        jScrollPane1.setRowHeaderView(numeracion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        jScrollPane1.setViewportView(txtTexto);

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        divTexto.manejarTexto(tabla, txtTexto.getText());
        AnalizadorLexico lexer = new AnalizadorLexico(new StringReader(codigoJava));

        AnalizadorLexico2 lexer2 = new AnalizadorLexico2(new StringReader(codigoPython));

        AnalizadorLexico3 lexer3 = new AnalizadorLexico3(new StringReader(codigoVb));
        
        AnalizadorLexico4 lexer4 = new AnalizadorLexico4(new StringReader(codigoC));
        try {
            
            /*System.out.println("codigo python------------------");
            System.out.println(codigoPython);
            System.out.println("codgio java---------------");
            System.out.println(codigoJava);
            System.out.println("codigo c-------------------------");
            System.out.println(codigoC);
            System.out.println("codigo Vb-----------------------------");
            System.out.println(codigoVb);*/
            //--------------------------------------------------------------------------------------------------------------
            // System.out.println(codigoVb);
            new SintaxVB(lexer3, tabla.getObVb(), tabla).parse();
           // new SintaxPYTHON(lexer2, tabla).parse();
         //   new SintaxJAVA(lexer, tabla).parse();
            //new SintaxC(lexer4, tabla).parse();

            //CUARPETA JAVA    
           /* for (int i = 0; i < tabla.getObJava().getCuarpeta().size(); i++) {
                System.out.println(tabla.getObJava().getCuarpeta().get(i).getOperacion()+" - "+tabla.getObJava().getCuarpeta().get(i).getDato1()+" - "+tabla.getObJava().getCuarpeta().get(i).getDato2()+" - "+tabla.getObJava().getCuarpeta().get(i).getVar()+" - "+tabla.getObJava().getCuarpeta().get(i).getNivel());
            }*/

            //CUARPETA VB
            for (int i = 0; i < tabla.getObVb().getCuarpeta().size(); i++) {
                System.out.println(tabla.getObVb().getCuarpeta().get(i).getOperacion()+" - "+tabla.getObVb().getCuarpeta().get(i).getDato1()+ " - "+tabla.getObVb().getCuarpeta().get(i).getDato2()+" - "+tabla.getObVb().getCuarpeta().get(i).getVar()+" - "+tabla.getObVb().getCuarpeta().get(i).getNivel());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
