/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Tablas.TablaSimbolos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisGonzalez
 */
public class TablaDatos extends javax.swing.JDialog {

    private TablaSimbolos tabla;
    
    /**
     * Creates new form TablaDatos
     */
    public TablaDatos(java.awt.Frame parent, boolean modal, TablaSimbolos tabla) {
        super(parent, modal);
        initComponents();
        this.tabla = tabla;
        setLocationRelativeTo(null);
        cargarTabla();
    }

    public void cargarTabla(){
        DefaultTableModel dtmModel = (DefaultTableModel) tablaDatos.getModel();
        Object[] fila = new Object[dtmModel.getColumnCount()];
        for (int i = 0; i < tabla.getTablaExe().size(); i++) {
            fila[0] = tabla.getTablaExe().get(i).getId();
            fila[1] = tabla.getTablaExe().get(i).getTipo();
            fila[2] = tabla.getTablaExe().get(i).getPosMemoria();
            fila[3] = tabla.getTablaExe().get(i).getAmbito();
            fila[4] = tabla.getTablaExe().get(i).getSize();
            fila[5] = tabla.getTablaExe().get(i).isEsArreglo();
            fila[6] = tabla.getTablaExe().get(i).getRol();
            fila[7] = tabla.getTablaExe().get(i).getLenguaje();
            dtmModel.addRow(fila);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "PosMemoria", "Ambito", "Size", "esArreglo", "Rol", "Lenguaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
